{{- if ne .Values.mode "disabled" }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: asklake-clickhouse-v2
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "asklake-realtime.labels" . | nindent 4 }}
    app.kubernetes.io/component: clickhouse
automountServiceAccountToken: false
{{- if .Values.kafkaConnect.createServiceAccount }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.kafkaConnect.serviceAccountName }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "asklake-realtime.labels" . | nindent 4 }}
    app.kubernetes.io/component: kafka-connect
automountServiceAccountToken: false
{{- end }}
{{- end }}
