{{- if and (ne .Values.mode "disabled") .Values.kafkaConnect.createServiceAccount }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.kafkaConnect.serviceAccountName }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "asklake-realtime.labels" . | nindent 4 }}
    app.kubernetes.io/component: kafka-connect
automountServiceAccountToken: true
{{- end }}
