import { Check, ChevronRight, Database, Hash, Plus, Save, ShieldCheck, Sparkles, Trash2, Workflow } from "lucide-react";
import { useMemo, useState } from "react";
import type { AuditResult, CatalogDataset } from "../../types";
import type { PermissionAction, PermissionGrant } from "../../types/permissions";
import { semanticLayerMocks, type SemanticLayerModel, type SemanticMetric } from "../../data/semanticLayerMock";
import { Badge } from "../../components/ui/badge";
import { Button } from "../../components/ui/button";
import { Panel } from "../../components/ui/panel";
import { Boxes, CircleUser } from "../../vendor/lucide";

type SemanticTab = "overview" | "metrics" | "dimensions" | "relationships" | "vocabulary" | "access";
const accessActions: PermissionAction[] = ["view", "query", "manage", "share"];
const accessActionLabels: Record<PermissionAction, string> = { view: "View", query: "Query", run: "Run", manage: "Manage", delete: "Delete", share: "Share" };

function principalLabel(grant: PermissionGrant) {
  if (grant.principalType === "public") return "전체 사용자";
  if (grant.principalId === "analytics-team") return "Analytics Team";
  if (grant.principalId === "finance-team") return "Finance Team";
  return grant.principalId;
}

function cloneModels() {
  return semanticLayerMocks.map((model) => ({
    ...model, linkedDatasetIds: [...model.linkedDatasetIds], synonyms: [...model.synonyms],
    metrics: model.metrics.map((metric) => ({ ...metric })), dimensions: model.dimensions.map((dimension) => ({ ...dimension, synonyms: [...dimension.synonyms] })),
    relationships: model.relationships.map((relationship) => ({ ...relationship })), permissionGrants: model.permissionGrants.map((grant) => ({ ...grant, actions: [...grant.actions] })),
  }));
}

function nextMetric(index: number): SemanticMetric {
  return { id: `metric-draft-${index}`, name: `new_metric_${index}`, label: "새 Metric", definition: "아직 정의되지 않은 Metric입니다.", expression: "COUNT(*)", format: "정수", status: "draft" };
}

export function SemanticLayerPage({ datasets, onAction, onAskAssistant }: { datasets: CatalogDataset[]; onAction: (action: string, apiPath: string, targetId: string, result?: AuditResult) => void; onAskAssistant: (prompt: string) => void }) {
  const [models, setModels] = useState<SemanticLayerModel[]>(cloneModels);
  const [selectedId, setSelectedId] = useState(models[0]?.id ?? "");
  const [activeTab, setActiveTab] = useState<SemanticTab>("overview");
  const [savedAt, setSavedAt] = useState("저장되지 않은 변경 없음");
  const selected = models.find((model) => model.id === selectedId) ?? models[0];
  const selectedDatasetNames = useMemo(() => selected?.linkedDatasetIds.map((id) => datasets.find((dataset) => dataset.id === id)?.name ?? id) ?? [], [datasets, selected]);
  if (!selected) return null;

  const updateSelected = (update: (model: SemanticLayerModel) => SemanticLayerModel) => {
    setModels((current) => current.map((model) => model.id === selected.id ? update(model) : model));
    setSavedAt("저장되지 않은 변경");
  };
  const createModel = () => {
    const next: SemanticLayerModel = { id: `semantic-draft-${Date.now()}`, name: "새 Semantic Dataset", description: "업무 용어와 Dataset을 연결해 보세요.", purpose: "이 모델이 답할 질문과 사용할 Dataset을 정의해 보세요.", questionExamples: ["어떤 질문에 답할 수 있나요?"], owner: "현재 사용자", updatedAt: "방금 생성", status: "draft", linkedDatasetIds: [], metrics: [], dimensions: [], relationships: [], synonyms: [], permissionGrants: [] };
    setModels((current) => [next, ...current]); setSelectedId(next.id); setActiveTab("overview"); onAction("semantic_layer.created", "/mock/semantic-layers", next.id);
  };
  const saveSelected = () => { setSavedAt("방금 저장됨 · Mock 상태"); onAction("semantic_layer.saved", "/mock/semantic-layers", selected.id, "success"); };
  const publishSelected = () => { updateSelected((model) => ({ ...model, status: "published", updatedAt: "방금 Publish" })); setSavedAt("Publish 완료 · Mock 상태"); onAction("semantic_layer.published", "/mock/semantic-layers", selected.id, "success"); };
  const addMetric = () => { updateSelected((model) => ({ ...model, metrics: [...model.metrics, nextMetric(model.metrics.length + 1)] })); setActiveTab("metrics"); };
  const updateAccessGrant = (grantId: string, action: PermissionAction, checked: boolean) => updateSelected((model) => ({ ...model, permissionGrants: model.permissionGrants.map((grant) => grant.id !== grantId ? grant : { ...grant, actions: checked ? [...new Set([...grant.actions, action])] : grant.actions.filter((item) => item !== action) }) }));
  const addAccessRule = () => { const next: PermissionGrant = { id: `semantic-access-${Date.now()}`, principalId: "new-team", principalType: "group", actions: ["view", "query"] }; updateSelected((model) => ({ ...model, permissionGrants: [...model.permissionGrants, next] })); setActiveTab("access"); };

  const labels: Record<SemanticTab, string> = {
    overview: "모델 요약", metrics: `계산 지표 ${selected.metrics.length}`, dimensions: `분석 기준 ${selected.dimensions.length}`,
    relationships: `데이터 연결 ${selected.relationships.length}`, vocabulary: `업무 용어 ${selected.synonyms.length}`, access: `권한 ${selected.permissionGrants.length}`,
  };

  return (
    <section className="semantic-layer-page" aria-label="Semantic Layer 관리">
      <header className="semantic-page-header"><div className="semantic-page-heading"><h1>Semantic Layer</h1><p>이 업무 모델은 어떤 질문에 답하고, 어떤 데이터를 사용할지 정의합니다.</p></div><div className="semantic-header-actions"><span className="semantic-save-state">{savedAt}</span><Button className="semantic-action-button" size="lg" type="button" variant="outline" onClick={createModel}><Plus /> 새 Semantic Dataset</Button><Button className="semantic-action-button" size="lg" type="button" variant="outline" onClick={saveSelected}><Save /> 저장</Button><Button className="semantic-action-button" size="lg" type="button" onClick={publishSelected}><Check /> Publish</Button></div></header>
      <div className="semantic-layer-layout">
        <Panel asChild className="semantic-model-list" overflow="visible"><aside aria-label="업무 모델 목록"><div className="semantic-list-heading"><div><span className="semantic-section-label">업무 모델</span><strong>{models.length}개 모델</strong><small className="semantic-model-list-hint">질문에 사용할 모델을 선택하세요.</small></div><button className="icon-button" type="button" title="Semantic Dataset 추가" onClick={createModel}><Plus size={16} /></button></div><div className="semantic-model-items">{models.map((model) => <button className={model.id === selected.id ? "semantic-model-item active" : "semantic-model-item"} key={model.id} type="button" onClick={() => setSelectedId(model.id)}><span className="semantic-model-icon"><Sparkles size={15} /></span><span className="semantic-model-copy"><strong>{model.name}</strong><small>{model.linkedDatasetIds.length} datasets · {model.metrics.length} metrics</small></span><ChevronRight size={15} /></button>)}</div><div className="semantic-list-note"><span className="semantic-status-dot published" /> Publish된 모델만 통합 챗봇에서 사용됩니다.</div></aside></Panel>
        <Panel asChild className="semantic-editor" overflow="visible"><main><div className="semantic-editor-topline"><div><Badge className="semantic-status-badge" size="sm" variant={selected.status === "published" ? "success" : "warning"}>{selected.status === "published" ? "Published" : "Draft"}</Badge><span className="semantic-updated">최근 수정 {selected.updatedAt}</span></div><button className="text-button" type="button" onClick={() => onAskAssistant(`${selected.name} Semantic Dataset의 핵심 Metric 정의와 사용 예시를 설명해줘`)}><Sparkles size={14} /> 챗봇으로 테스트</button></div><div className="semantic-model-form"><label><span>이름</span><input value={selected.name} onChange={(event) => updateSelected((model) => ({ ...model, name: event.target.value }))} /></label><label><span>설명</span><textarea rows={2} value={selected.description} onChange={(event) => updateSelected((model) => ({ ...model, description: event.target.value }))} /></label></div><div className="semantic-tab-list" role="tablist" aria-label="Semantic Layer 편집 탭">{(Object.keys(labels) as SemanticTab[]).map((tab) => <button aria-selected={activeTab === tab} className={activeTab === tab ? "semantic-tab active" : "semantic-tab"} key={tab} role="tab" type="button" onClick={() => setActiveTab(tab)}>{labels[tab]}</button>)}</div>

          {activeTab === "overview" && <div className="semantic-model-overview"><Panel asChild className="semantic-purpose-panel" overflow="visible"><section><div className="semantic-purpose-heading"><div><span className="semantic-section-label">MODEL SUMMARY</span><h2>{selected.name}</h2><p>{selected.purpose}</p></div><Badge size="sm" variant={selected.status === "published" ? "success" : "warning"}>{selected.status === "published" ? "통합 챗봇 사용 중" : "Publish 후 챗봇에 사용"}</Badge></div><div className="semantic-summary-grid"><div className="semantic-summary-block"><div className="semantic-summary-block-header"><span className="semantic-summary-label">사용 데이터</span><button className="text-button" type="button" onClick={() => setActiveTab("relationships")}>데이터 연결 편집 <ChevronRight size={14} /></button></div>{selected.linkedDatasetIds.length ? <ul className="semantic-dataset-summary-list">{selected.linkedDatasetIds.map((id) => { const dataset = datasets.find((item) => item.id === id); return <li key={id}><Database size={15} /><span><strong>{dataset?.name ?? id}</strong><small>{dataset ? `${dataset.layer} · ${dataset.rows}` : "Catalog Dataset"}</small></span></li>; })}</ul> : <div className="semantic-empty-inline">연결된 Dataset이 없습니다. 데이터 연결에서 추가하세요.</div>}</div></div></section></Panel><div className="semantic-summary-counts" aria-label="모델 정의 수"><div className="semantic-summary-count"><strong>{selected.metrics.length}</strong><span>계산 지표</span></div><div className="semantic-summary-count"><strong>{selected.dimensions.length}</strong><span>분석 기준</span></div><div className="semantic-summary-count"><strong>{selected.relationships.length}</strong><span>데이터 연결</span></div><div className="semantic-summary-count"><strong>{selected.synonyms.length}</strong><span>업무 용어</span></div></div></div>}
          {activeTab === "metrics" && <div className="semantic-definition-table"><div className="semantic-table-heading"><div><span className="semantic-section-label">METRICS</span><h2>계산 지표 정의</h2></div><Button className="semantic-inline-action" size="sm" type="button" variant="outline" onClick={addMetric}><Plus /> Metric 추가</Button></div><p className="semantic-subsection-copy">자연어 질문이 SQL로 바뀔 때 참조되는 공식 정의입니다.</p>{selected.metrics.map((metric) => <article className="semantic-definition-row" key={metric.id}><div className="semantic-definition-icon"><Sparkles size={15} /></div><div className="semantic-definition-copy"><div><strong>{metric.label}</strong><code>{metric.name}</code><span className={metric.status === "ready" ? "semantic-mini-status ready" : "semantic-mini-status draft"}>{metric.status === "ready" ? "Ready" : "Draft"}</span></div><p>{metric.definition}</p><small>{metric.expression} · {metric.format}</small></div><button className="icon-button danger" type="button" title="Metric 삭제" onClick={() => updateSelected((model) => ({ ...model, metrics: model.metrics.filter((item) => item.id !== metric.id) }))}><Trash2 size={15} /></button></article>)}</div>}
          {activeTab === "dimensions" && <div className="semantic-definition-table"><div className="semantic-table-heading"><div><span className="semantic-section-label">DIMENSIONS</span><h2>분석 기준 정의</h2></div></div><p className="semantic-subsection-copy">지역, 날짜, 상태처럼 질문을 해석할 기준입니다.</p>{selected.dimensions.map((dimension) => <article className="semantic-definition-row" key={dimension.id}><div className="semantic-definition-icon"><Hash size={15} /></div><div className="semantic-definition-copy"><div><strong>{dimension.label}</strong><code>{dimension.name}</code></div><p>{dimension.source}</p><small>{dimension.synonyms.join(" · ")}</small></div></article>)}</div>}
          {activeTab === "relationships" && <div className="semantic-relationship-page"><Panel asChild className="semantic-subsection" overflow="visible"><section><div className="semantic-subsection-heading"><div><span className="semantic-section-label">CATALOG DATASETS</span><h2>사용 데이터</h2></div><Database size={18} /></div><p className="semantic-subsection-copy">이 모델이 질문에 답할 때 조회할 Catalog Dataset을 선택합니다.</p><div className="semantic-linked-datasets">{datasets.map((dataset) => { const checked = selected.linkedDatasetIds.includes(dataset.id); return <label className={checked ? "semantic-linked-dataset selected" : "semantic-linked-dataset"} key={dataset.id}><input checked={checked} type="checkbox" onChange={() => updateSelected((model) => ({ ...model, linkedDatasetIds: checked ? model.linkedDatasetIds.filter((id) => id !== dataset.id) : [...model.linkedDatasetIds, dataset.id] }))} /><span className="semantic-checkbox">{checked ? <Check size={12} /> : null}</span><span><strong>{dataset.name}</strong><small>{dataset.layer} · {dataset.rows}</small></span></label>; })}</div></section></Panel><div className="semantic-definition-table"><div className="semantic-table-heading"><div><span className="semantic-section-label">JOIN RELATIONSHIPS</span><h2>관계 정의</h2></div><Workflow size={18} /></div><p className="semantic-subsection-copy">여러 Dataset을 함께 사용할 때 허용할 Join 관계를 제한적으로 정의합니다.</p>{selected.relationships.length ? selected.relationships.map((relationship) => <article className="semantic-definition-row relationship" key={relationship.id}><div className="semantic-definition-icon"><Workflow size={15} /></div><div className="semantic-definition-copy"><div><strong>{relationship.label}</strong><span className="semantic-mini-status ready">{relationship.cardinality}</span></div><p>{relationship.left}</p><small>↕ {relationship.right}</small></div></article>) : <div className="semantic-empty-state"><Workflow size={22} /><strong>아직 관계가 없습니다.</strong><span>관련 Dataset을 연결하면 제한된 Join 관계를 정의할 수 있습니다.</span></div>}</div></div>}
          {activeTab === "vocabulary" && <Panel asChild className="semantic-subsection semantic-vocabulary-page" overflow="visible"><section><div className="semantic-subsection-heading"><div><span className="semantic-section-label">BUSINESS VOCABULARY</span><h2>업무 용어와 동의어</h2></div><Hash size={18} /></div><p className="semantic-subsection-copy">챗봇이 같은 의미로 인식할 단어를 등록합니다.</p><div className="semantic-tag-list">{selected.synonyms.map((synonym) => <span className="semantic-tag" key={synonym}>{synonym}<button type="button" aria-label={`${synonym} 삭제`} onClick={() => updateSelected((model) => ({ ...model, synonyms: model.synonyms.filter((item) => item !== synonym) }))}><Trash2 size={12} /></button></span>)}</div><input className="semantic-inline-input" placeholder="동의어를 입력하고 Enter" onKeyDown={(event) => { if (event.key === "Enter" && event.currentTarget.value.trim()) { const value = event.currentTarget.value.trim(); updateSelected((model) => ({ ...model, synonyms: model.synonyms.includes(value) ? model.synonyms : [...model.synonyms, value] })); event.currentTarget.value = ""; } }} /></section></Panel>}
          {activeTab === "access" && <div className="semantic-access-page"><div className="semantic-table-heading"><div><span className="semantic-section-label">ACCESS</span><h2>Semantic Dataset 권한</h2></div><Button className="semantic-inline-action" size="sm" type="button" variant="outline" onClick={addAccessRule}><Plus /> 권한 규칙 추가</Button></div><p className="semantic-subsection-copy">이 모델을 조회하거나 통합 챗봇의 컨텍스트로 사용할 주체를 제한합니다.</p><Panel asChild className="semantic-access-panel" overflow="visible"><section><div className="semantic-access-table-head"><span>주체</span><span>권한</span><span aria-hidden="true" /></div>{selected.permissionGrants.length ? selected.permissionGrants.map((grant) => <div className="semantic-access-row" key={grant.id}><div className="semantic-access-principal"><span className="semantic-access-principal-icon">{grant.principalType === "group" ? <Boxes size={16} /> : grant.principalType === "public" ? <ShieldCheck size={16} /> : <CircleUser size={16} />}</span><div><strong>{principalLabel(grant)}</strong><small>{grant.principalType === "group" ? "그룹" : grant.principalType === "public" ? "전체" : "사용자"}</small></div></div><div className="semantic-access-actions">{accessActions.map((action) => { const checked = grant.actions.includes(action); return <label className={checked ? "semantic-access-toggle checked" : "semantic-access-toggle"} key={action}><input checked={checked} type="checkbox" onChange={(event) => updateAccessGrant(grant.id ?? "", action, event.target.checked)} /><span>{accessActionLabels[action]}</span></label>; })}</div><button aria-label={`${principalLabel(grant)} 권한 규칙 삭제`} className="icon-button danger" title="권한 규칙 삭제" type="button" onClick={() => updateSelected((model) => ({ ...model, permissionGrants: model.permissionGrants.filter((item) => item.id !== grant.id) }))}><Trash2 size={15} /></button></div>) : <div className="semantic-empty-state"><ShieldCheck size={22} /><strong>권한 규칙이 없습니다.</strong><span>권한 규칙을 추가해야 이 모델을 사용할 수 있습니다.</span></div>}</section></Panel></div>}
          <footer className="semantic-editor-footer"><span><Database size={14} /> 연결 Dataset: {selectedDatasetNames.join(", ") || "없음"}</span></footer>
        </main></Panel>
      </div>
    </section>
  );
}
