from sqlalchemy import JSON, Boolean, Float, ForeignKey, Integer, String, Text
from sqlalchemy.orm import Mapped, mapped_column

from app.models.base import Base, TimestampMixin


class ETLJobModel(TimestampMixin, Base):
    __tablename__ = "etl_jobs"

    id: Mapped[str] = mapped_column(String(120), primary_key=True)
    name: Mapped[str] = mapped_column(String(255), nullable=False, index=True)
    owner: Mapped[str] = mapped_column(String(255), nullable=False)
    created_by: Mapped[str | None] = mapped_column(String(255), nullable=True)
    created_by_profile: Mapped[dict | None] = mapped_column(JSON, nullable=True)
    status: Mapped[str] = mapped_column(String(64), nullable=False, default="scheduled")
    tag: Mapped[str] = mapped_column(String(64), nullable=False, default="[생성]")
    source: Mapped[str] = mapped_column(String(255), nullable=False)
    target: Mapped[str] = mapped_column(String(255), nullable=False, index=True)
    schedule: Mapped[str] = mapped_column(String(255), nullable=False)
    schedule_policy: Mapped[dict | None] = mapped_column(JSON, nullable=True)
    schedule_summary: Mapped[str | None] = mapped_column(Text, nullable=True)
    retry_policy: Mapped[dict | None] = mapped_column(JSON, nullable=True)
    retry_policy_summary: Mapped[str | None] = mapped_column(String(255), nullable=True)
    run_limit_summary: Mapped[str | None] = mapped_column(String(255), nullable=True)
    source_config: Mapped[list[list[str]]] = mapped_column(JSON, nullable=False, default=list)
    source_label: Mapped[str] = mapped_column(String(255), nullable=False)
    source_type: Mapped[str] = mapped_column(String(120), nullable=False)
    schema_columns: Mapped[list[dict]] = mapped_column(JSON, nullable=False, default=list)
    schema_fingerprint: Mapped[str | None] = mapped_column(Text, nullable=True)
    schema_sample_rows: Mapped[list[list[str]]] = mapped_column(JSON, nullable=False, default=list)
    permission_roles: Mapped[list[dict] | None] = mapped_column(JSON, nullable=True)
    storage_type: Mapped[str | None] = mapped_column(String(64), nullable=True)
    partition: Mapped[str | None] = mapped_column(String(255), nullable=True)
    partition_columns: Mapped[list[str] | None] = mapped_column(JSON, nullable=True)
    index_columns: Mapped[list[str] | None] = mapped_column(JSON, nullable=True)
    compression: Mapped[str | None] = mapped_column(String(64), nullable=True)
    storage_path: Mapped[str | None] = mapped_column(String(512), nullable=True)
    target_description: Mapped[str | None] = mapped_column(Text, nullable=True)
    target_tags: Mapped[list[str] | None] = mapped_column(JSON, nullable=True)
    target_format: Mapped[str] = mapped_column(String(120), nullable=False)
    target_layer: Mapped[str] = mapped_column(String(32), nullable=False)
    target_path: Mapped[str | None] = mapped_column(String(512), nullable=True)
    rag: Mapped[bool] = mapped_column(Boolean, default=False, nullable=False)
    transform_output_columns: Mapped[list[list[str]]] = mapped_column(JSON, nullable=False, default=list)
    transform_steps: Mapped[list[dict]] = mapped_column(JSON, nullable=False, default=list)
    text_structuring_spec_id: Mapped[str | None] = mapped_column(String(120), nullable=True, index=True)
    text_structuring_spec_version: Mapped[int | None] = mapped_column(Integer, nullable=True)
    text_structuring_spec_fingerprint: Mapped[str | None] = mapped_column(String(64), nullable=True)
    text_structuring_definition_snapshot: Mapped[dict | None] = mapped_column(JSON, nullable=True)
    quality_invalid_rows: Mapped[list[list[str]]] = mapped_column(JSON, nullable=False, default=list)
    quality_rules: Mapped[list[dict]] = mapped_column(JSON, nullable=False, default=list)
    quality_score: Mapped[float | None] = mapped_column(Float, nullable=True)
    quality_status: Mapped[str | None] = mapped_column(String(32), nullable=True)
    last_run: Mapped[str] = mapped_column(String(64), nullable=False)
    last_state: Mapped[str] = mapped_column(Text, nullable=False)
    next_run: Mapped[str] = mapped_column(String(255), nullable=False)
    progress: Mapped[dict | None] = mapped_column(JSON, nullable=True)
    stats: Mapped[dict] = mapped_column(JSON, nullable=False, default=dict)
    dag_steps: Mapped[list[dict]] = mapped_column(JSON, nullable=False, default=list)
    dag_steps_by_run_id: Mapped[dict | None] = mapped_column(JSON, nullable=True)
    dataset_id: Mapped[str | None] = mapped_column(String(120), nullable=True, index=True)


class ETLRunModel(TimestampMixin, Base):
    __tablename__ = "etl_runs"

    run_id: Mapped[str] = mapped_column(String(120), primary_key=True)
    job_id: Mapped[str] = mapped_column(String(120), ForeignKey("etl_jobs.id"), nullable=False, index=True)
    status: Mapped[str] = mapped_column(String(64), nullable=False)
    started_at: Mapped[str] = mapped_column(String(64), nullable=False)
    ended_at: Mapped[str] = mapped_column(String(64), nullable=False)
    duration: Mapped[str] = mapped_column(String(120), nullable=False)
    input_rows: Mapped[str] = mapped_column(String(120), nullable=False)
    output_rows: Mapped[str] = mapped_column(String(120), nullable=False)
    output_path: Mapped[str | None] = mapped_column(String(512), nullable=True)
    failed_stage: Mapped[str] = mapped_column(Text, nullable=False)
    error_summary: Mapped[str] = mapped_column(Text, nullable=False)
    airflow_dag_id: Mapped[str | None] = mapped_column(String(255), nullable=True)
    airflow_dag_run_id: Mapped[str | None] = mapped_column(String(255), nullable=True, index=True)
    airflow_run_url: Mapped[str | None] = mapped_column(String(1024), nullable=True)
    airflow_state: Mapped[str | None] = mapped_column(String(64), nullable=True)
    task_states: Mapped[dict | None] = mapped_column(JSON, nullable=True)
    last_synced_at: Mapped[str | None] = mapped_column(String(64), nullable=True)
    sync_error: Mapped[str | None] = mapped_column(String(512), nullable=True)
