export const seedJobs = [
  {
    id: "JOB-001",
    name: "daily_order_ingestion",
    owner: "admin",
    status: "scheduled",
    tag: "[orders]",
    source: "PostgreSQL / commerce.orders",
    target: "orders_clean",
    schedule: "Daily 00:00",
    lastRun: "2026-07-03 00:03",
    lastState: "success",
    nextRun: "2026-07-04 00:00",
  },
  {
    id: "JOB-002",
    name: "s3_user_log_parse",
    owner: "data-team",
    status: "failed",
    tag: "[logs]",
    source: "S3 / raw/user-log/*.csv",
    target: "user_activity",
    schedule: "Every hour",
    lastRun: "2026-07-03 10:10",
    lastState: "failed - age TYPE_CAST",
    nextRun: "2026-07-03 11:10",
  },
  {
    id: "JOB-003",
    name: "realtime_clickstream_ingestion",
    owner: "platform",
    status: "running",
    tag: "[stream]",
    source: "Kafka / clickstream.events",
    target: "clickstream_events",
    schedule: "Streaming",
    lastRun: "running now",
    lastState: "5/8 steps - Load to Lake",
    nextRun: "-",
    progress: {
      label: "5/8 steps - Load to Lake",
      value: 62,
    },
  },
  {
    id: "JOB-004",
    name: "daily_sales_aggregation",
    owner: "analytics",
    status: "scheduled",
    tag: "[mart]",
    source: "Lake / orders_clean",
    target: "sales_daily_summary",
    schedule: "Daily 01:00",
    lastRun: "2026-07-03 01:05",
    lastState: "success",
    nextRun: "2026-07-04 01:00",
  },
];

export const seedDatasets = [
  {
    id: "ds_customer_orders_gold",
    name: "orders_clean",
    description: "Cleaned customer order data from all commerce channels.",
    owner: "Data Platform Team",
    layer: "GOLD",
    status: "available",
    freshness: "latest",
    source: "daily_order_ingestion",
    rows: "12.4M rows",
    size: "18.2GB",
    quality: "98% (Excellent)",
    lastUpdated: "2026-07-03 00:03",
    nextRefresh: "2026-07-04 00:00",
    rag: true,
    tags: ["#customer", "#sales", "#orders"],
    schema: [["order_id", "string"], ["customer_id", "string"], ["order_date", "timestamp"], ["total_amount", "decimal"], ["status", "string"]],
    sampleRows: [["ORD-1001", "CUS-204", "2026-07-02", "128000", "paid"], ["ORD-1002", "CUS-118", "2026-07-02", "56000", "shipped"]],
    upstream: ["PostgreSQL commerce.orders", "daily_order_ingestion"],
    downstream: ["SQL Analysis", "Order Dashboard", "customer_ltv_mart"],
  },
  {
    id: "ds_user_activity",
    name: "user_activity",
    description: "Normalized user behavior data parsed from S3 CSV logs.",
    owner: "data-team",
    layer: "SILVER",
    status: "approval_required",
    freshness: "approval",
    source: "s3_user_log_parse",
    rows: "0 rows",
    size: "0B",
    quality: "74% (Needs review)",
    lastUpdated: "2026-07-03 10:10",
    nextRefresh: "retry approval required",
    rag: false,
    tags: ["#log", "#behavior", "#review-required"],
    schema: [["user_id", "string"], ["age", "integer"], ["event_name", "string"], ["event_time", "timestamp"], ["raw_value", "string"]],
    sampleRows: [["-", "-", "-", "-", "Transform failed"], ["-", "-", "-", "-", "age TYPE_CAST"]],
    upstream: ["S3 raw/user-log/*.csv", "s3_user_log_parse"],
    downstream: ["SQL Analysis", "User Behavior Report"],
  },
  {
    id: "ds_clickstream_events",
    name: "clickstream_events",
    description: "Realtime web and mobile clickstream events.",
    owner: "platform",
    layer: "SILVER",
    status: "available",
    freshness: "latest",
    source: "realtime_clickstream_ingestion",
    rows: "142,030 rows",
    size: "820MB",
    quality: "91% (Good)",
    lastUpdated: "running now",
    nextRefresh: "Streaming",
    rag: false,
    tags: ["#behavior", "#stream", "#click"],
    schema: [["event_id", "string"], ["user_id", "string"], ["event_time", "timestamp"], ["page_url", "string"], ["raw_payload", "json"]],
    sampleRows: [["EVT-881", "CUS-204", "2026-07-03 10:21", "/pricing", "click"], ["EVT-882", "CUS-118", "2026-07-03 10:22", "/checkout", "view"]],
    upstream: ["Kafka clickstream.events", "realtime_clickstream_ingestion"],
    downstream: ["Realtime SQL", "Growth dashboard"],
  },
  {
    id: "ds_sales_daily_summary",
    name: "sales_daily_summary",
    description: "Daily sales summary mart by date and region.",
    owner: "analytics",
    layer: "GOLD",
    status: "available",
    freshness: "latest",
    source: "daily_sales_aggregation",
    rows: "1.8M rows",
    size: "2.4GB",
    quality: "96% (Excellent)",
    lastUpdated: "2026-07-03 01:05",
    nextRefresh: "2026-07-04 01:00",
    rag: true,
    tags: ["#sales", "#dw", "#daily"],
    schema: [["sales_date", "date"], ["region", "string"], ["gross_sales", "decimal"], ["order_count", "integer"], ["status", "string"]],
    sampleRows: [["2026-07-01", "KR", "31800000", "12800", "paid"], ["2026-07-02", "JP", "11200000", "4210", "paid"]],
    upstream: ["Lake orders_clean", "daily_sales_aggregation"],
    downstream: ["Sales Dashboard", "SQL Analysis"],
  },
  {
    id: "ds_customer_review_gold",
    name: "customer_review_gold",
    description: "Gold layer customer review data with sentiment labels.",
    owner: "analytics",
    layer: "GOLD",
    status: "available",
    freshness: "stale",
    source: "customer_review_gold_pipeline",
    rows: "4.2M rows",
    size: "1.8GB",
    quality: "95% (Good)",
    lastUpdated: "2026-07-02 18:30",
    nextRefresh: "manual run",
    rag: true,
    tags: ["#customer", "#RAG", "#review"],
    schema: [["review_id", "bigint"], ["product_id", "string"], ["rating", "int"], ["review_text", "string"], ["sentiment", "string"]],
    sampleRows: [["RV-991", "SKU-200", "5", "Fast delivery", "positive"], ["RV-992", "SKU-118", "2", "Packaging was damaged", "negative"]],
    upstream: ["S3 Raw reviews", "customer_review_gold_pipeline"],
    downstream: ["AI Search", "Review Analytics Dashboard", "SQL Analysis"],
  },
];

export const seedDashboards = [
  { id: "dash_sales_demo", name: "Sales Analytics Demo 2026-06-26 22:04:05", tags: "Sales|Revenue|Demo", owner: "Admin User", createdAt: "2026-06-26 22:04", createdAtValue: "2026-06-26T22:04:05.000Z", updated: "2 hours ago", updatedAtValue: "2026-07-04T13:46:00.000Z", status: "published", meta: "Last 7 days - auto refresh", datasetId: "ds_sales_daily_summary", widgets: ["kpi", "bar", "line", "table"] },
  { id: "dash_marketing_roi", name: "Marketing Campaign ROI Tracking", tags: "Marketing|ROI", owner: "Jane Doe", createdAt: "2026-06-20 10:12", createdAtValue: "2026-06-20T10:12:00.000Z", updated: "yesterday", updatedAtValue: "2026-07-03T16:30:00.000Z", status: "draft", meta: "Permission review needed", datasetId: "ds_clickstream_events", widgets: ["kpi", "bar"] },
  { id: "dash_qbr", name: "Executive QBR Dashboard", tags: "Executive|Quarterly", owner: "Robert Wilson", createdAt: "2026-06-18 09:00", createdAtValue: "2026-06-18T09:00:00.000Z", updated: "3 days ago", updatedAtValue: "2026-07-01T11:20:00.000Z", status: "published", meta: "Connected to GOLD mart", datasetId: "ds_sales_daily_summary", widgets: ["kpi", "line", "donut"] },
  { id: "dash_apac_sales", name: "Regional Sales Performance - APAC", tags: "Regional|Sales", owner: "Sarah Kim", createdAt: "2026-06-12 14:45", createdAtValue: "2026-06-12T14:45:00.000Z", updated: "1 week ago", updatedAtValue: "2026-06-27T15:05:00.000Z", status: "published", meta: "Shared with APAC sales", datasetId: "ds_sales_daily_summary", widgets: ["bar", "table"] },
  { id: "dash_inventory_leakage", name: "Inventory Leakage Report", tags: "Inventory|Ops", owner: "Michael Chen", createdAt: "2026-06-05 08:20", createdAtValue: "2026-06-05T08:20:00.000Z", updated: "2 weeks ago", updatedAtValue: "2026-06-20T18:10:00.000Z", status: "draft", meta: "Operations review in progress", datasetId: "ds_customer_orders_gold", widgets: ["table"] },
  { id: "dash_customer_health", name: "Customer Health Monitor", tags: "Customer|Health|Ops", owner: "Admin User", createdAt: "2026-06-02 13:10", createdAtValue: "2026-06-02T13:10:00.000Z", updated: "2 weeks ago", updatedAtValue: "2026-06-19T09:40:00.000Z", status: "published", meta: "Shared with CS team", datasetId: "ds_customer_review_gold", widgets: ["kpi", "donut"] },
  { id: "dash_finance_close", name: "Monthly Finance Close", tags: "Finance|Monthly", owner: "Jane Doe", createdAt: "2026-05-29 17:35", createdAtValue: "2026-05-29T17:35:00.000Z", updated: "3 weeks ago", updatedAtValue: "2026-06-15T12:05:00.000Z", status: "draft", meta: "Month-end review", datasetId: "ds_sales_daily_summary", widgets: ["kpi", "table"] },
  { id: "dash_growth_funnel", name: "Growth Funnel Snapshot", tags: "Growth|Funnel|Marketing", owner: "Sarah Kim", createdAt: "2026-05-24 11:25", createdAtValue: "2026-05-24T11:25:00.000Z", updated: "3 weeks ago", updatedAtValue: "2026-06-11T10:15:00.000Z", status: "published", meta: "Campaign data linked", datasetId: "ds_clickstream_events", widgets: ["line", "donut"] },
  { id: "dash_support_sla", name: "Support SLA Tracker", tags: "Support|SLA|Ops", owner: "Robert Wilson", createdAt: "2026-05-21 16:00", createdAtValue: "2026-05-21T16:00:00.000Z", updated: "1 month ago", updatedAtValue: "2026-06-04T15:45:00.000Z", status: "published", meta: "Weekly ops review", datasetId: "ds_user_activity", widgets: ["kpi", "table"] },
  { id: "dash_logistics_cost", name: "Logistics Cost Overview", tags: "Logistics|Cost", owner: "Michael Chen", createdAt: "2026-05-17 09:30", createdAtValue: "2026-05-17T09:30:00.000Z", updated: "1 month ago", updatedAtValue: "2026-05-31T08:55:00.000Z", status: "draft", meta: "Cost estimate tracking", datasetId: "ds_customer_orders_gold", widgets: ["bar"] },
  { id: "dash_retention_cohort", name: "Retention Cohort Analysis", tags: "Retention|Cohort|Customer", owner: "Jane Doe", createdAt: "2026-05-12 14:05", createdAtValue: "2026-05-12T14:05:00.000Z", updated: "1 month ago", updatedAtValue: "2026-05-29T18:20:00.000Z", status: "published", meta: "Customer retention analysis", datasetId: "ds_clickstream_events", widgets: ["line", "table"] },
  { id: "dash_procurement_risk", name: "Procurement Risk Board", tags: "Procurement|Risk|Ops", owner: "Admin User", createdAt: "2026-05-08 10:50", createdAtValue: "2026-05-08T10:50:00.000Z", updated: "1 month ago", updatedAtValue: "2026-05-24T13:30:00.000Z", status: "draft", meta: "Supplier risk board", datasetId: "ds_customer_orders_gold", widgets: ["kpi", "bar"] },
  { id: "dash_mobile_quality", name: "Mobile Quality Dashboard", tags: "Mobile|Quality", owner: "Sarah Kim", createdAt: "2026-05-03 15:20", createdAtValue: "2026-05-03T15:20:00.000Z", updated: "2 months ago", updatedAtValue: "2026-05-18T16:10:00.000Z", status: "published", meta: "App quality tracking", datasetId: "ds_clickstream_events", widgets: ["kpi", "line"] },
  { id: "dash_data_quality", name: "Data Quality Operations", tags: "Data|Quality|Ops", owner: "Robert Wilson", createdAt: "2026-04-28 08:15", createdAtValue: "2026-04-28T08:15:00.000Z", updated: "2 months ago", updatedAtValue: "2026-05-10T09:05:00.000Z", status: "published", meta: "Automated quality scoring", datasetId: "ds_user_activity", widgets: ["kpi", "table"] },
  { id: "dash_ad_spend", name: "Ad Spend Efficiency", tags: "Marketing|Spend|ROI", owner: "Michael Chen", createdAt: "2026-04-22 12:40", createdAtValue: "2026-04-22T12:40:00.000Z", updated: "2 months ago", updatedAtValue: "2026-05-04T14:25:00.000Z", status: "draft", meta: "Ad efficiency tracking", datasetId: "ds_clickstream_events", widgets: ["bar", "donut"] },
];
