global:
  environment: dev
  clusterName: ""
  kafkaRuntime: msk-serverless
  kafkaAuth: iam
  continuousOwner: ec2-mvp

namespace:
  create: true
  name: asklake-dev
  labels: {}

serviceAccounts:
  frontend:
    create: true
    name: asklake-frontend
    annotations: {}
    automountServiceAccountToken: false
  backend:
    create: true
    name: asklake-backend
    annotations: {}
    automountServiceAccountToken: false
  airflow:
    create: true
    name: asklake-airflow
    annotations: {}
    automountServiceAccountToken: false
  spark:
    create: true
    name: asklake-spark
    annotations: {}
    automountServiceAccountToken: false
