apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: asklake-spark-driver
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "asklake-workloads.commonLabels" . | nindent 4 }}
    app.kubernetes.io/component: spark
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["create", "get", "list", "watch", "delete"]
  - apiGroups: [""]
    resources: ["services", "configmaps"]
    verbs: ["create", "get", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: asklake-spark-driver
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "asklake-workloads.commonLabels" . | nindent 4 }}
    app.kubernetes.io/component: spark
subjects:
  - kind: ServiceAccount
    name: {{ .Values.sparkApplication.serviceAccountName }}
    namespace: {{ .Values.namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: asklake-spark-driver
