enabled: false
environment: ""

nodeRoleName: ""

selectors:
  subnets: {}
  securityGroups: {}

networkPolicy:
  mode: ""
  eventLogs: ""

general:
  capacityTypes: []
  instanceCategories: []
  instanceGenerationMin: 0
  limits:
    cpu: ""
    memory: ""
  disruption:
    consolidationPolicy: ""
    consolidateAfter: ""
    budget: ""
  expireAfter: ""
  terminationGracePeriod: ""

spark:
  capacityTypes: []
  instanceCategories: []
  instanceGenerationMin: 0
  limits:
    cpu: ""
    memory: ""
  disruption:
    consolidationPolicy: ""
    consolidateAfter: ""
    budget: ""
  expireAfter: ""
  terminationGracePeriod: ""
