installCRDs: true

crds:
  createClusterExternalSecret: false
  createClusterSecretStore: false
  createClusterGenerator: false
  createClusterPushSecret: false
  createPushSecret: false
  createSecretStore: true

scopedRBAC: true
scopedNamespace: asklake-dev
processClusterExternalSecret: false
processClusterPushSecret: false
processClusterStore: false
processClusterGenerator: false
processPushSecret: false
processSecretStore: true
leaderElect: false

rbac:
  create: true
  serviceAccountTokenCreate: false
  servicebindings:
    create: false
  aggregateToView: false
  aggregateToEdit: false

serviceAccount:
  create: true
  automount: true
  name: asklake-external-secrets

resources:
  requests:
    cpu: 20m
    memory: 64Mi
  limits:
    cpu: 200m
    memory: 256Mi

webhook:
  create: false

certController:
  create: false
