connector.name=iceberg
iceberg.catalog.type=jdbc
iceberg.jdbc-catalog.driver-class=org.postgresql.Driver
iceberg.jdbc-catalog.connection-url=jdbc:postgresql://postgres:5432/${ENV:TRINO_ICEBERG_JDBC_DATABASE}
iceberg.jdbc-catalog.connection-user=${ENV:TRINO_ICEBERG_JDBC_USER}
iceberg.jdbc-catalog.connection-password=${ENV:TRINO_ICEBERG_JDBC_PASSWORD}
iceberg.jdbc-catalog.catalog-name=${ENV:TRINO_ICEBERG_CATALOG_NAME}
iceberg.jdbc-catalog.default-warehouse-dir=s3://${ENV:TRINO_ICEBERG_WAREHOUSE_BUCKET}/${ENV:TRINO_ICEBERG_WAREHOUSE_PREFIX}
iceberg.file-format=PARQUET
fs.s3.enabled=true
s3.region=${ENV:TRINO_S3_REGION}
s3.path-style-access=false
