import { Boxes, CircleUser, Database, PanelRight, Plus, Send, Sparkles, Trash2, X } from "lucide-react";
import { useEffect, useMemo, useRef, useState } from "react";
import type { AuditResult, CatalogDataset, FlowId } from "../../types";
import askLakeNessiIconUrl from "../../assets/asklake-nessi-icon.png";

const STORAGE_KEY = "asklake.mock.global-assistant.v1";
type AssistantMessage = { id: string; role: "assistant" | "user"; content: string; context: string[]; sql?: string; sources?: string[] };
type AssistantConversation = { id: string; title: string; messages: AssistantMessage[] };
export type AssistantPageContext = { flow: FlowId; label: string; datasetName?: string; semanticName?: string };
type PersistedAssistantState = { conversations: AssistantConversation[]; activeConversationId: string };
function NessieIcon({ className }: { className: string }) { return <img alt="" aria-hidden="true" className={className} src={askLakeNessiIconUrl} />; }
function makeConversation(): AssistantConversation { return { id: `mock-conversation-${Date.now()}-${Math.random().toString(36).slice(2, 7)}`, title: "새 대화", messages: [] }; }
function loadState(): PersistedAssistantState { const fallback = () => { const conversation = makeConversation(); return { conversations: [conversation], activeConversationId: conversation.id }; }; if (typeof window === "undefined") return fallback(); try { const parsed = JSON.parse(window.localStorage.getItem(STORAGE_KEY) ?? "null") as Partial<PersistedAssistantState> | null; if (!parsed?.conversations?.length) return fallback(); const active = parsed.conversations.some((item) => item.id === parsed.activeConversationId) ? parsed.activeConversationId! : parsed.conversations[0].id; return { conversations: parsed.conversations, activeConversationId: active }; } catch { return fallback(); } }
function titleFromPrompt(prompt: string) { const normalized = prompt.replace(/\s+/g, " ").trim(); return normalized.length > 26 ? `${normalized.slice(0, 26)}…` : normalized || "새 대화"; }
function mockAnswer(prompt: string, context: AssistantPageContext) { if (context.flow === "semantic") return { content: `${context.semanticName ?? "선택한 업무 모델"} 기준으로 답변하는 Mock입니다.\n\nPublish된 지표와 연결 Dataset을 기준으로 질문을 해석합니다.`, sources: ["업무 모델 정의", "Catalog Dataset"] }; if (context.flow === "sql" || prompt.toLowerCase().includes("sql")) return { content: "현재 화면의 Dataset 범위에서 작성한 Mock SQL입니다.", sql: "SELECT\n  region,\n  SUM(total_amount) AS gross_sales\nFROM orders_clean\nGROUP BY region;", sources: ["SQL Analysis 컨텍스트"] }; return { content: `현재 ${context.label} 화면을 기준으로 질문을 해석했습니다. 이 응답은 프론트 Mock입니다.`, sources: [context.label, context.datasetName ?? "현재 화면"] }; }

export function GlobalAssistantWidget({ context, datasets, request, onAction }: { context: AssistantPageContext; datasets: CatalogDataset[]; request?: { key: number; prompt: string }; onAction: (action: string, apiPath: string, targetId: string, result?: AuditResult) => void }) {
  const initial = useRef<PersistedAssistantState | null>(null); if (!initial.current) initial.current = loadState();
  const [conversations, setConversations] = useState(initial.current.conversations); const [activeConversationId, setActiveConversationId] = useState(initial.current.activeConversationId); const [isOpen, setIsOpen] = useState(false); const [draft, setDraft] = useState(""); const [pending, setPending] = useState(false); const composerRef = useRef<HTMLTextAreaElement | null>(null); const timerRef = useRef<number | null>(null); const lastRequest = useRef<number | null>(null);
  const activeConversation = conversations.find((conversation) => conversation.id === activeConversationId) ?? conversations[0];
  const contextChips = useMemo(() => [context.label, context.datasetName, context.semanticName].filter(Boolean) as string[], [context]);
  const suggestions = context.flow === "semantic" ? ["이 업무 모델의 정의를 보여줘", "연결된 Dataset을 설명해줘", "Publish 전에 확인할 항목은?"] : ["현재 화면을 요약해줘", "관련 지표를 찾아줘", "다음 작업을 추천해줘"];
  useEffect(() => { try { window.localStorage.setItem(STORAGE_KEY, JSON.stringify({ conversations, activeConversationId })); } catch { /* best effort */ } }, [conversations, activeConversationId]);
  useEffect(() => () => { if (timerRef.current !== null) window.clearTimeout(timerRef.current); }, []);
  useEffect(() => { if (!request || request.key === lastRequest.current) return; lastRequest.current = request.key; setIsOpen(true); setDraft(request.prompt); window.setTimeout(() => composerRef.current?.focus(), 0); }, [request]);
  const updateActive = (update: (conversation: AssistantConversation) => AssistantConversation) => setConversations((current) => current.map((conversation) => conversation.id === activeConversation.id ? update(conversation) : conversation));
  const submitPrompt = () => { const prompt = draft.trim(); if (!prompt || pending) return; const contextAtSend = { ...context }; const chips = [...contextChips]; const conversationId = activeConversation.id; const userMessage: AssistantMessage = { id: `user-${Date.now()}`, role: "user", content: prompt, context: chips }; setConversations((current) => current.map((conversation) => conversation.id === conversationId ? { ...conversation, title: conversation.messages.length ? conversation.title : titleFromPrompt(prompt), messages: [...conversation.messages, userMessage] } : conversation)); setDraft(""); setPending(true); timerRef.current = window.setTimeout(() => { const response = mockAnswer(prompt, contextAtSend); setConversations((current) => current.map((conversation) => conversation.id === conversationId ? { ...conversation, messages: [...conversation.messages, { id: `assistant-${Date.now()}`, role: "assistant", content: response.content, context: chips, sql: response.sql, sources: response.sources }] } : conversation)); setPending(false); onAction("assistant.mock.message_created", "/mock/assistant/chat", conversationId, "success"); }, 500); };
  const startNew = () => { const next = makeConversation(); setConversations((current) => [next, ...current]); setActiveConversationId(next.id); setDraft(""); onAction("assistant.mock.conversation_created", "/mock/assistant/conversations", next.id); };
  const deleteCurrent = () => { const remaining = conversations.filter((conversation) => conversation.id !== activeConversation.id); const next = remaining[0] ?? makeConversation(); setConversations(remaining.length ? remaining : [next]); setActiveConversationId(next.id); onAction("assistant.mock.conversation_deleted", "/mock/assistant/conversations", activeConversation.id); };
  return <div className={isOpen ? "global-assistant is-open" : "global-assistant"}>
    {!isOpen && <button className="assistant-launcher" type="button" aria-label="통합 챗봇 열기" onClick={() => { setIsOpen(true); window.setTimeout(() => composerRef.current?.focus(), 0); }}><span className="assistant-launcher-glow" /><NessieIcon className="assistant-nessie-launcher" /><span className="assistant-launcher-label">AskLake<br /><strong>Assistant</strong></span><span className="assistant-launcher-badge">MOCK</span></button>}
    {isOpen && <section className="global-assistant-panel" aria-label="AskLake 통합 챗봇"><header className="assistant-panel-header"><div className="assistant-panel-title"><span><Sparkles size={14} /> AskLake Assistant <em>MOCK</em></span><strong>통합 챗봇</strong><small>{context.label} 컨텍스트를 사용 중</small></div><div className="assistant-panel-actions"><button className="icon-button" type="button" title="새 대화" onClick={startNew}><Plus size={16} /></button><button className="icon-button" type="button" title="대화 삭제" onClick={deleteCurrent}><Trash2 size={15} /></button><button className="icon-button" type="button" title="챗봇 접기" onClick={() => setIsOpen(false)}><X size={17} /></button></div></header><div className="assistant-context-strip"><span><PanelRight size={13} /> 현재 페이지</span>{contextChips.map((chip) => <strong key={chip}>{chip}</strong>)}</div><div className="assistant-message-list">{activeConversation.messages.length === 0 && <div className="assistant-empty-state"><span className="assistant-empty-icon"><NessieIcon className="assistant-nessie-empty" /></span><strong>현재 화면에서 바로 물어보세요</strong><p>페이지가 바뀌어도 이 대화는 유지됩니다.</p></div>}{activeConversation.messages.map((message) => <article className={`assistant-message ${message.role}`} key={message.id}>{message.role === "assistant" ? <span className="assistant-message-avatar"><NessieIcon className="assistant-nessie-avatar" /></span> : <span className="assistant-message-avatar user"><CircleUser size={14} /></span>}<div className="assistant-message-body"><p>{message.content}</p>{message.sql && <pre><code>{message.sql}</code></pre>}{message.sources?.length ? <div className="assistant-sources">{message.sources.map((source) => <span key={source}><Boxes size={11} /> {source}</span>)}</div> : null}</div></article>)}{pending && <div className="assistant-pending"><NessieIcon className="assistant-nessie-pending" /><span>현재 화면을 확인하는 중…</span><i /><i /><i /></div>}</div><div className="assistant-suggestion-list">{suggestions.map((suggestion) => <button disabled={pending} key={suggestion} type="button" onClick={() => { setDraft(suggestion); composerRef.current?.focus(); }}>{suggestion}</button>)}</div><footer className="assistant-composer"><div className="assistant-dataset-hint"><Database size={13} /> {datasets.length}개 Catalog Dataset을 Mock 컨텍스트로 사용</div><div className="assistant-composer-row"><textarea ref={composerRef} aria-label="통합 챗봇 질문" placeholder="현재 화면에 대해 질문하세요" rows={2} value={draft} onChange={(event) => setDraft(event.target.value)} onKeyDown={(event) => { if (event.key === "Enter" && !event.shiftKey) { event.preventDefault(); submitPrompt(); } }} /><button aria-label="질문 보내기" disabled={pending || !draft.trim()} type="button" onClick={submitPrompt}><Send size={16} /></button></div><small>Enter 전송 · Shift + Enter 줄바꿈 · 백엔드 연결 전 Mock 응답</small></footer></section>}
  </div>;
}
