apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: asklake-secrets-manager
  namespace: asklake-dev
spec:
  provider:
    aws:
      service: SecretsManager
      region: ap-northeast-2
