apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: asklake-backend-runtime
  namespace: asklake-dev
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: SecretStore
    name: asklake-secrets-manager
  target:
    name: asklake-backend-runtime
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      type: Opaque
  data:
    - secretKey: DATABASE_URL
      remoteRef:
        key: asklake/dev/backend/runtime
        property: DATABASE_URL
    - secretKey: BOOTSTRAP_ADMIN_PASSWORD
      remoteRef:
        key: asklake/dev/backend/runtime
        property: BOOTSTRAP_ADMIN_PASSWORD
