apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: asklake-spark-runtime
  namespace: asklake-dev
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: SecretStore
    name: asklake-secrets-manager
  target:
    name: asklake-spark-runtime
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      type: Opaque
  data:
    - secretKey: ASKLAKE_SPARK_ICEBERG_JDBC_URL
      remoteRef:
        key: asklake/dev/spark/runtime
        property: ASKLAKE_SPARK_ICEBERG_JDBC_URL
    - secretKey: ASKLAKE_SPARK_ICEBERG_JDBC_USER
      remoteRef:
        key: asklake/dev/spark/runtime
        property: ASKLAKE_SPARK_ICEBERG_JDBC_USER
    - secretKey: ASKLAKE_SPARK_ICEBERG_JDBC_PASSWORD
      remoteRef:
        key: asklake/dev/spark/runtime
        property: ASKLAKE_SPARK_ICEBERG_JDBC_PASSWORD
