apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: asklake-trino-runtime
  namespace: asklake-dev
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: SecretStore
    name: asklake-secrets-manager
  target:
    name: asklake-trino-runtime
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      type: Opaque
  data:
    - secretKey: TRINO_ICEBERG_JDBC_URL
      remoteRef:
        key: asklake/dev/trino/runtime
        property: TRINO_ICEBERG_JDBC_URL
    - secretKey: TRINO_ICEBERG_JDBC_USER
      remoteRef:
        key: asklake/dev/trino/runtime
        property: TRINO_ICEBERG_JDBC_USER
    - secretKey: TRINO_ICEBERG_JDBC_PASSWORD
      remoteRef:
        key: asklake/dev/trino/runtime
        property: TRINO_ICEBERG_JDBC_PASSWORD
    - secretKey: TRINO_TLS_KEYSTORE_PASSWORD
      remoteRef:
        key: asklake/dev/trino/runtime
        property: TRINO_TLS_KEYSTORE_PASSWORD
    - secretKey: TRINO_INTERNAL_SHARED_SECRET
      remoteRef:
        key: asklake/dev/trino/runtime
        property: TRINO_INTERNAL_SHARED_SECRET
    - secretKey: trino-keystore.jks
      remoteRef:
        key: asklake/dev/trino/runtime
        property: trino-keystore.jks
        decodingStrategy: Base64
    - secretKey: trino-password.db
      remoteRef:
        key: asklake/dev/trino/runtime
        property: trino-password.db
