coordinator=true
node-scheduler.include-coordinator=true
http-server.https.enabled=true
http-server.https.port=8443
http-server.https.keystore.path=/etc/trino/tls/keystore.jks
http-server.https.keystore.key=${ENV:TRINO_TLS_KEYSTORE_PASSWORD}
http-server.authentication.type=PASSWORD
internal-communication.shared-secret=${ENV:TRINO_INTERNAL_SHARED_SECRET}
internal-communication.https.required=true
discovery.uri=https://trino:8443
